version: '3.1'
services:      
  demo-sytem-logging:
    container_name: demo-sytem-logging
    build:
      context: ./../batchs/demo-sytem-logging
      dockerfile: Dockerfile
    image: bacelarnetto/demo-sytem-logging:latest
    environment:
      TZ: America/Sao_Paulo
    networks:
      - batch-network

  spring-batch-demo-one:
    container_name: spring-batch-demo-one
    build:
      context: ./../batchs/spring-batch-demo-one
      dockerfile: Dockerfile
    image: bacelarnetto/spring-batch-demo-one:latest
    environment:
      TZ: America/Sao_Paulo
    networks:
      - batch-network
      
networks:
  batch-network:
      driver: bridge